# WARNING: Trying to run docker-compose from within VS Code on Windows will throw an obscure error. Run it from a PowerShell window instead
# https://github.com/docker/compose/issues/5019
version: '3'
services:
  app:
    build: .
    depends_on: 
    - database
    env_file: env.live.yml
    environment:
      COUCHDB_URL: "database:5984"
    ports:
    - "3000:3000"
    volumes:
    - logvolume01:/var/log
    restart: unless-stopped
    command: ["./wait-for-it.sh", "database:5984", "--", "./dist/server"]
  database:
    image: klaemo/couchdb
    ports: 
    - "3001:5984" # Expose the database to the host machine on localhost:3001
volumes:
  logvolume01: {}